# -*- coding: utf-8 -*-
"""numpy functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GzKEaiiR95pLmY3Y4_nMoCE3Tx9t3Xr9
"""

import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

#convert multidimensioned array to single dimensione

arr=np.array([
              [1,2],
              [3,4,],
              [4,5]])

print(arr.ndim)

print(arr.shape)

print(arr.size)

arr.ravel()

print(arr)

arr=arr.ravel()

print(arr)

arr=[
     [1,2,3],
     [4,5,6],
     [7,8,9]
]

print(arr)

max=np.max(arr)

print(max)

##################### MINIMUM

min=np.min(arr)
print(min)

max_index=np.argmax(arr)
print(max_index)

cols_max=np.max(arr,axis=0)
print(cols_max)

rows_max=np.max(arr,axis=1)
print(rows_max)

